---
# Fail the role if it runs on an unsupported platform
- name: Assert platform is supported
  assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']
      - ansible_architecture in ['x86_64']
  tags:
    - java

# Load version specific variables
- name: Load version variables
  include_vars: "versions/{{ jdk_version }}.yml"
  tags:
    - java

# this directory will contain the Java downloads
- name: Check java download directory (local)
  local_action: file state=directory mode=0755 dest={{ jdk_download_dir }}
  tags:
    - java

- name: Get oracle java package stat (local)
  local_action: stat path={{ jdk_download_dir }}/{{ oracle_jdk_pkg_name }} get_md5=yes
  register: oracle_jdk_pkg
  ignore_errors: true
  tags:
    - java


- name: Download oracle java  package (local)
  local_action: command curl
    --location
    --insecure
    --remote-name
    --cookie oraclelicense=accept-securebackup-cookie
    --cookie-jar {{ jdk_download_dir }}/{{ oracle_jdk_pkg_name }}.cookie
    {{ oracle_jdk_pkg_mirror }}
    chdir={{ jdk_download_dir }}
  register: oracle_jdk_pkg_download
  when: not oracle_jdk_pkg.stat.exists or oracle_jdk_pkg.stat.md5 != "{{ oracle.md5_checksum }}"
  tags:
    - java


- name: Get oracle java package stat (local)
  local_action: stat path={{ jdk_download_dir }}/{{ oracle_jdk_pkg_name }}
  register: oracle_jdk_pkg
  ignore_errors: true
  when: oracle_jdk_pkg_download|changed
  tags:
    - java

- name: Verify oracle java package md5sum (local)
  fail: msg="uncompleted java package"
  when:
    - oracle_jdk_pkg_download|changed
    - not oracle_jdk_pkg.stat.exists or oracle_jdk_pkg.stat.md5 != "{{ oracle.md5_checksum }}"
  tags:
    - java

- name: Check java install dir
  file: state=directory mode=0755 dest={{ install_dir }}
  tags: java

- name: Install oracle java to remote nodes
  unarchive:
    src={{ jdk_download_dir }}/{{ oracle_jdk_pkg_name }}
    dest={{ install_dir }}
    mode=0755
    creates={{ install_dir }}/{{ oracle_jdk_dir_name }}
  tags: java

- name: Set JAVA_HOME ansible fact
  set_fact:
    java_home={{ install_dir }}/{{ oracle_jdk_dir_name }}
  tags: java


- name: Add java path to profile system-wide
  sudo: yes
  template: src=java.sh.j2 dest=/etc/profile.d/java.sh owner=root group=root mode=0755
  tags:
    - java
